import js from '@eslint/js';
import tseslint from 'typescript-eslint';
import prettier from 'eslint-config-prettier';

export default tseslint.config(
  {
    ignores: [
      '**/node_modules/**',
      '**/dist/**',
      '**/.next/**',
      '**/coverage/**',
      'docs/reference/**',
      // Generated by `next build`; contains triple-slash references by design.
      '**/next-env.d.ts',
    ],
  },
  js.configs.recommended,
  ...tseslint.configs.recommended,
  {
    rules: {
      // Hard rule: no `any`, no unchecked casts across the wire (CLAUDE.md).
      '@typescript-eslint/no-explicit-any': 'error',
      // Hard rule: named exports only.
      'no-restricted-syntax': [
        'error',
        {
          selector: 'ExportDefaultDeclaration',
          message: 'Named exports only — no default exports.',
        },
      ],
      '@typescript-eslint/no-unused-vars': [
        'error',
        { argsIgnorePattern: '^_', varsIgnorePattern: '^_' },
      ],
    },
  },
  {
    // packages/crdt is dependency-free and I/O-free. That constraint is load-bearing:
    // it is what makes the in-process multi-replica fuzzer possible (SPEC §10).
    files: ['packages/crdt/src/**/*.ts'],
    rules: {
      // Enforced structurally: a bare-specifier import in src/ means a dependency.
      'no-restricted-syntax': [
        'error',
        {
          selector: 'ExportDefaultDeclaration',
          message: 'Named exports only — no default exports.',
        },
        {
          selector: 'ImportDeclaration[source.value=/^[^.]/]',
          message: 'packages/crdt imports nothing. See CLAUDE.md hard rule 1 and SPEC §10.',
        },
      ],
      'no-restricted-globals': [
        'error',
        { name: 'fetch', message: 'packages/crdt performs no I/O (SPEC §10).' },
        { name: 'setTimeout', message: 'packages/crdt is pure and clock-free (SPEC §10).' },
        { name: 'Date', message: 'Logical time only — Lamport clocks, never wall clocks.' },
      ],
    },
  },
  {
    // Tool config files (drizzle, next, playwright) require default exports.
    files: [
      '**/*.config.ts',
      '**/*.config.mts',
      '**/*.config.mjs',
      '**/*.config.js',
      'vitest.workspace.ts',
    ],
    rules: {
      'no-restricted-syntax': 'off',
    },
  },
  {
    files: ['apps/web/**/*.tsx', 'apps/web/**/*.ts'],
    rules: {
      // Next.js requires default exports for pages, layouts and route segments.
      'no-restricted-syntax': 'off',
    },
  },
  prettier,
);
